{% set name = "cpuid" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cpuid-{{ version }}.tar.gz
  sha256: e4e098dd7e0a76c16058306106c764a594d19c19d6577b905c8b2effb71e616c
  patches:
    - 0001-remove-readme.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.3
  run:
    - cpuid-native >=0.0.7
    - python >=3.3

test:
  imports:
    - cpuid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fpelliccioni/cpuid-py
  summary: cpuid Pythonic API
  license: MIT
  license_file: LICENSE
extra:
  recipe-maintainers:
    - thewchan
